### PR TITLE
Complete website branch

### PR DESCRIPTION
**Pull request by zhorabay**
- [ ] In this branch, we:

- Modified the Awesome books application to have:
a) A Navigation bar.
b) Three content sections:
Books list.
Add book form.
Contact info.

-Used the given wireframe as a guide.

-Used only plain JavaScript and CSS.

### CODE REVIEW

**Review by ridwanediallo — APPROVED** [review]
# STATUS: APPROVED 🟢
## Hi @zhorabay and @bhushan354 , 
Congratulations!GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- The navigation is added and working as expected. ✔ 💪 💪
- You successfully completed all the requirements.  🎉 🎉 🎉 ✔

## Optional suggestions

- [**OPTIONAL**]  You successfully completed all of the milestone requirements 👏 💪. That's fantastic 🤗. However, adding and removing books is no longer possible. So, in order to have a complete and functional app, I believe it would be a good idea to figure out what's wrong and fix it. 👌🙂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by enniopo** [comment]
Hi @zhorabay @bhushan354 - I wanted to ask you to please implement the changes marked as OPTIONAL by @ridwanediallo. 
The app was working correctly in the previous PR. However, while working on this PR, you introduced a bug, and the add-removing functionality is no longer working. This is a very important functionality, and you should make sure to implement it correctly.

**Comment by zhorabay** [comment]
@enniopo Could you help us with solving the problem? Because we see everything is correct, even console in the browser shows correct, but we still can't add a book. Could you find our issue and guide us,please?

**Comment by enniopo** [comment]
@zhorabay restart your localstorage to see the error we are talking about.
Also, they can [book a meeting](https://calendly.com/ahmt9417/one-on-one-meetings?month=2023-08&date=2023-08-10) with one of the Senior CR to get some help.

**Pull request merged**
